name: Test Falso
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v
